#!/system/bin/sh

#Exports
setenforce 0
export bin=/system/bin
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export USER=root
export LOGNAME=root
unset LD_PRELOAD

#Mounts
busybox mount -o remount,suid /data
busybox mountpoint -q /data/local/ubuntu/dev
busybox mount -o bind /dev /data/local/ubuntu/dev
busybox mount -t devpts devpts /data/local/ubuntu/dev/pts
busybox mount -t proc proc /data/local/ubuntu/proc
busybox mount -t sysfs sysfs /data/local/ubuntu/sys
busybox mount -t tmpfs none /data/local/ubuntu/tmp
busybox chmod 666 /dev/null
busybox sysctl -w net.ipv4.ip_forward=1

#Chrooting
clear
busybox chroot /data/local/ubuntu /bin/login -f root